### ISSUE TITLE
additional spectrum to mean spectrum 

### ISSUE THREAD

**Issue by czubert** [czubert/SERSitiVIS#9]
Possibility to add additional spectrum to mean spectrum, so you can prepare mean spectrum and add background spectrum to it, or RAMAN spectrum, for better visualisation

**Comment by charzu** [comment]
Nie widzą zysku, tylko komplikacje.
Niech użytkownik sobie zrobi uśrednione, pobierze a potem wrzuci uśrednione i referencyjne do innego wykresu.
Bo inaczej zrobi się nieczytelnie.
